# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: 163daka

on:
  schedule:
    #国际标准时间21点00分，北京时间需要+8小时，代表北京时间次日6点运行，延迟20m，6.2*
    - cron: "0 22 * * *"
  
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    
    - name: Run
      env:
        APP_ID: ${{secrets.APP_ID}}
        TO_USER: ${{secrets.TO_USER}}
        APP_SECRET: ${{secrets.APP_SECRET}}
        API: ${{secrets.API}}
        PHONE: ${{secrets.PHONE}}
        PASSWORD: ${{secrets.PASSWORD}}
        TEMPLATE_ID: ${{secrets.TEMPLATE_ID}}
        
      run: 
       python3 mypy.py
       
    - name: Push log #更新日志
      uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: push
